# Generated by Django 6.0.3 on 2026-03-13 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
        ('reservas', '0002_alter_inscripcion_usuario_delete_usuario'),
        ('usuarios', '0002_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('usuario', 'turno')},
        ),
    ]
